# 300+ Unique Appium Android Mobile E2E Test Case Definitions for PostureFixPro Mobile App

APPIUM_MOBILE_TEST_CASES = [
    # --- Biometric Auth & Security (25) ---
    ("Biometric Auth", "Fingerprint Sensor Prompt Trigger on Launch", "High"),
    ("Biometric Auth", "Face Unlock Dashboard Authentication", "High"),
    ("Biometric Auth", "Failed Biometric Fallback to 4-Digit PIN", "High"),
    ("Biometric Auth", "Hardware Unavailable Fallback to Password", "Medium"),
    ("Biometric Auth", "Invalid 4-Digit PIN Toast Error Alert", "High"),
    ("Biometric Auth", "Auto-Lock Mobile App on 60s Idle Time", "High"),
    ("Biometric Auth", "Android Keystore Encrypted Access Token Storage", "High"),
    ("Biometric Auth", "Recents Switcher Thumbnail Privacy Masking", "Medium"),
    ("Biometric Auth", "Security Settings Biometric Toggle Switch", "Medium"),
    ("Biometric Auth", "Password Reset Biometric Re-Authentication", "High"),
    ("Biometric Auth", "Encrypted SQLite DB Initialization on First Boot", "High"),
    ("Biometric Auth", "Certificate Pinning HTTPS Connection Gate", "High"),
    ("Biometric Auth", "Root Detection Security Warning Display", "High"),
    ("Biometric Auth", "Anti-Tampering APK Integrity Signature Check", "High"),
    ("Biometric Auth", "Session Timeout Local Key Cache Purge", "Medium"),
    ("Biometric Auth", "SMS Verification Code PIN Reset Flow", "High"),
    ("Biometric Auth", "FLAG_SECURE Screen Capture Restriction Check", "Medium"),
    ("Biometric Auth", "Deep Link App Launch Intent Security Filter", "Medium"),
    ("Biometric Auth", "OAuth Refresh Token Removal on Logout", "High"),
    ("Biometric Auth", "Account Lockout After 5 Failed Attempts", "High"),
    ("Biometric Auth", "Pattern Lock Fallback for Legacy Devices", "Low"),
    ("Biometric Auth", "Prompt Cancellation Lock Screen Security", "Medium"),
    ("Biometric Auth", "Multi-User Profile Switching Session Separation", "Medium"),
    ("Biometric Auth", "Biometric Credential Update Event Handler", "High"),
    ("Biometric Auth", "Screen Reader Speech Output for Biometrics", "Low"),

    # --- Mobile Camera & Landmark Capture (30) ---
    ("Camera Landmark Capture", "Runtime CAMERA Permission Request Dialog", "High"),
    ("Camera Landmark Capture", "Front Selfie Camera Default Preview Stream", "High"),
    ("Camera Landmark Capture", "Rear Camera Switch Button Interaction", "High"),
    ("Camera Landmark Capture", "Camera2 API 60 FPS High Frame Rate Engine", "High"),
    ("Camera Landmark Capture", "MediaPipe Android GPU Acceleration Initialization", "High"),
    ("Camera Landmark Capture", "SurfaceView Render of 33 Pose Landmarks", "High"),
    ("Camera Landmark Capture", "Low-Light Indoor Camera Autofocus Adjustment", "Medium"),
    ("Camera Landmark Capture", "Flashlight Torch Toggle Button Activation", "Low"),
    ("Camera Landmark Capture", "Full Body Alignment Wizard Box Display", "High"),
    ("Camera Landmark Capture", "Neck-to-Ear Lateral Angle Step Guidance", "High"),
    ("Camera Landmark Capture", "Side-Profile Spine Curvature Wizard Step", "High"),
    ("Camera Landmark Capture", "HUD Overlay 30 FPS Live Posture Score Bar", "High"),
    ("Camera Landmark Capture", "Battery Saver Mode Resolution Scaling", "Medium"),
    ("Camera Landmark Capture", "Home Button Press Background Camera Pause", "High"),
    ("Camera Landmark Capture", "Foreground Resume Stream Re-Activation", "High"),
    ("Camera Landmark Capture", "Orientation Reflow Portrait to Landscape", "High"),
    ("Camera Landmark Capture", "Multi-Window Split Screen Preview Layout", "Medium"),
    ("Camera Landmark Capture", "Lens Occlusion Finger Detection Banner", "Medium"),
    ("Camera Landmark Capture", "Face Mesh and Body Pose Sync Tracking", "Medium"),
    ("Camera Landmark Capture", "Landmark Confidence Threshold Filter (>0.85)", "High"),
    ("Camera Landmark Capture", "Hardware In-Use Conflict Exception Handling", "High"),
    ("Camera Landmark Capture", "Thermal Throttling Frame Rate Downsampling", "Medium"),
    ("Camera Landmark Capture", "Snapshot Capture Saved to Local Gallery", "Medium"),
    ("Camera Landmark Capture", "Slouch Skeleton Color Shift Green to Red", "High"),
    ("Camera Landmark Capture", "Exposure Compensation Setting Slider", "Low"),
    ("Camera Landmark Capture", "Wide-Angle Lens Selection on Multi-Cam Devices", "Low"),
    ("Camera Landmark Capture", "Frame Drop Monitor (<5% Dropped Frames)", "Medium"),
    ("Camera Landmark Capture", "Light vs Heavy MediaPipe Model Switch", "Medium"),
    ("Camera Landmark Capture", "Aspect Ratio Aspect Fitting Without Distortion", "Medium"),
    ("Camera Landmark Capture", "Permission Denied Shortcut to Settings App", "High"),

    # --- Haptic & Vibration Slouch Feedback (20) ---
    ("Haptic Feedback", "Vibrator System Service Initialization", "High"),
    ("Haptic Feedback", "Short Double-Pulse Mild Slouch Warning", "High"),
    ("Haptic Feedback", "Long Continuous Pulse Severe Slouch Alert", "High"),
    ("Haptic Feedback", "Vibration Intensity Control Slider (Soft/Strong)", "Medium"),
    ("Haptic Feedback", "Alert Settings Haptic Feedback Master Toggle", "High"),
    ("Haptic Feedback", "Vibration Pattern Selector (Pulse/Heartbeat)", "Low"),
    ("Haptic Feedback", "Do Not Disturb (DND) Vibration Suppression", "High"),
    ("Haptic Feedback", "Test Vibration Sample Trigger Button", "Medium"),
    ("Haptic Feedback", "Active Phone Call Haptic Mute Protection", "High"),
    ("Haptic Feedback", "Wear OS Smartwatch Haptic Notification Sync", "Medium"),
    ("Haptic Feedback", "Slouch Warning Delay Control (1s to 5s)", "Medium"),
    ("Haptic Feedback", "Battery Optimization Haptic Impact (<1%/hr)", "Medium"),
    ("Haptic Feedback", "Hardware Missing Fallback to Audio Chime", "Low"),
    ("Haptic Feedback", "Daily Slouch Vibration Trigger Logging", "Low"),
    ("Haptic Feedback", "Scheduled Sleep Hours Haptic Suppression", "Medium"),
    ("Haptic Feedback", "Calibration Completion Haptic Confirmation", "Low"),
    ("Haptic Feedback", "UI Slider Touch Movement Haptic Tick", "Low"),
    ("Haptic Feedback", "Bottom Tab Bar Item Selection Haptic Click", "Low"),
    ("Haptic Feedback", "Pull-to-Refresh Threshold Haptic Pop", "Low"),
    ("Haptic Feedback", "Milestone Unlocked Haptic Reward Feedback", "Medium"),

    # --- Push Notifications & Background Service (25) ---
    ("Notifications & Background", "POST_NOTIFICATIONS Runtime Permission Prompt", "High"),
    ("Notifications & Background", "FCM Device Registration Token Ingestion", "High"),
    ("Notifications & Background", "Foreground Live Tracking Notification Channel", "High"),
    ("Notifications & Background", "Status Bar Ongoing Live Posture Score Tile", "High"),
    ("Notifications & Background", "Status Bar Notification Tap Screen Launcher", "High"),
    ("Notifications & Background", "Posture Slouch Warning Push Payload Processing", "High"),
    ("Notifications & Background", "Hourly Ergonomic Stretch Reminder Display", "Medium"),
    ("Notifications & Background", "Daily 6 PM Posture Digest Summary Notification", "Medium"),
    ("Notifications & Background", "Action Button 'Pause Tracking' Notification Execution", "High"),
    ("Notifications & Background", "Action Button 'Mute 1 Hr' Alert Suppression", "Medium"),
    ("Notifications & Background", "Doze Mode Background Service Survival", "High"),
    ("Notifications & Background", "WorkManager Periodic Background Sync Execution", "High"),
    ("Notifications & Background", "Custom Notification LED Flash Color Configuration", "Low"),
    ("Notifications & Background", "Ringtone Sound Selector Playback Preference", "Medium"),
    ("Notifications & Background", "Silent Notification Channel for Background Updates", "Low"),
    ("Notifications & Background", "Dismiss All Notifications Shade Action Handler", "Low"),
    ("Notifications & Background", "Slouch Warning Message Stacking and Grouping", "Medium"),
    ("Notifications & Background", "High Priority Channel Elevation for Slouch Alerts", "High"),
    ("Notifications & Background", "RECEIVE_BOOT_COMPLETED Auto-Start Service", "High"),
    ("Notifications & Background", "Tracking Stop Action Background Service Lifecycle", "High"),
    ("Notifications & Background", "FCM Wellness Tip Topic Subscription Sync", "Low"),
    ("Notifications & Background", "Launcher Icon Unread Notification Badge Count", "Medium"),
    ("Notifications & Background", "Deep Link Route Navigation From Push Payload", "High"),
    ("Notifications & Background", "App Diagnostic Notification Delivery Audit Log", "Low"),
    ("Notifications & Background", "Background Memory Retention Limit (<50MB Footprint)", "High"),

    # --- Gesture Navigation & Touch Targets (25) ---
    ("Gesture Navigation", "Swipe Left Route Transition Gesture", "High"),
    ("Gesture Navigation", "Swipe Right Back Navigation Transition", "Medium"),
    ("Gesture Navigation", "Pull-to-Refresh Analytics Dashboard Reload", "High"),
    ("Gesture Navigation", "Pinch-to-Zoom Posture Angle Chart Axis", "High"),
    ("Gesture Navigation", "Double-Tap Video Full Screen Mode Switch", "Medium"),
    ("Gesture Navigation", "Long-Press Session History Context Menu", "Medium"),
    ("Gesture Navigation", "Swipe-to-Delete Session List Item Action", "High"),
    ("Gesture Navigation", "Android Edge-to-Edge System Back Gesture", "High"),
    ("Gesture Navigation", "Bottom Sheet Swipe Down Dismissal", "High"),
    ("Gesture Navigation", "Kinetic Scroll Momentum on Long History Lists", "Medium"),
    ("Gesture Navigation", "Minimum 48x48dp Touch Target Size Compliance", "High"),
    ("Gesture Navigation", "Material Ripple Tap Effect Animation", "Low"),
    ("Gesture Navigation", "Button Double-Tap Prevention Safeguard", "High"),
    ("Gesture Navigation", "FAB Auto-Hide on List Scroll Down", "Low"),
    ("Gesture Navigation", "FAB Auto-Reveal on List Scroll Up", "Low"),
    ("Gesture Navigation", "Tab Bar Instant View Switch Without Flicker", "High"),
    ("Gesture Navigation", "Help Icon Long-Press Tooltip Popover", "Low"),
    ("Gesture Navigation", "Slider Thumb Drag Value Tracking", "Medium"),
    ("Gesture Navigation", "Multi-Touch Rejection During Active Calibration", "Medium"),
    ("Gesture Navigation", "Quick Swipe Velocity Threshold Recognition", "Low"),
    ("Gesture Navigation", "Hardware Back Button Close Drawer Navigation", "High"),
    ("Gesture Navigation", "Hardware Back Button App Exit Modal Prompt", "Medium"),
    ("Gesture Navigation", "Scroll Position Persistence on Route Return", "Medium"),
    ("Gesture Navigation", "Carousel Dots Indicator Slide Animation", "Low"),
    ("Gesture Navigation", "Accordion Panel Expand and Collapse Gesture", "Low"),

    # --- Bluetooth Posture Wearable Integration (20) ---
    ("Bluetooth Wearables", "Bluetooth LE Runtime Permission Request Prompt", "High"),
    ("Bluetooth Wearables", "Scanning Nearby PostureFixPro Smart Wearables", "High"),
    ("Bluetooth Wearables", "BLE Handshake and Security Pairing Bond", "High"),
    ("Bluetooth Wearables", "50Hz BLE Accelerometer Raw Sensor Stream", "High"),
    ("Bluetooth Wearables", "BLE Gyroscope Spinal Tilt Calculation Engine", "High"),
    ("Bluetooth Wearables", "Wearable Battery Percentage Status Bar Tile", "Medium"),
    ("Bluetooth Wearables", "BLE Disconnection Auto-Reconnect Backoff", "High"),
    ("Bluetooth Wearables", "Haptic Alert Command Transmission Over BLE", "High"),
    ("Bluetooth Wearables", "Over-The-Air (OTA) BLE Firmware Update Check", "Medium"),
    ("Bluetooth Wearables", "BLE Connection Loss Status Banner Alert", "High"),
    ("Bluetooth Wearables", "Spinal Angle Sensor Zeroing Calibration Button", "High"),
    ("Bluetooth Wearables", "Camera plus BLE Sensor Fusion Accuracy Boost", "High"),
    ("Bluetooth Wearables", "Packet Checksum CRC Integrity Verification", "Medium"),
    ("Bluetooth Wearables", "Wearable Device Unpairing and MAC Removal", "Medium"),
    ("Bluetooth Wearables", "Signal Strength (RSSI) Signal Level Gauge", "Low"),
    ("Bluetooth Wearables", "Background BLE Telemetry Sync Service Status", "High"),
    ("Bluetooth Wearables", "Multiple Wearable Device Pairing Conflict Handling", "Low"),
    ("Bluetooth Wearables", "Passkey Input Pairing Authentication Screen", "High"),
    ("Bluetooth Wearables", "Encrypted Local SQLite BLE Telemetry Logging", "Medium"),
    ("Bluetooth Wearables", "Wearable Device Sleep Mode Interrupt Wakeup", "Medium"),

    # --- Offline Local Database Sync (25) ---
    ("Offline Sync", "SQLite DB Schema Migration Version 1 to 2", "High"),
    ("Offline Sync", "Offline Session Saving to Local Encrypted Database", "High"),
    ("Offline Sync", "Airplane Mode Network Status Banner Toggle", "High"),
    ("Offline Sync", "Network Reconnection Automatic Sync Dispatcher", "High"),
    ("Offline Sync", "Backend HTTP 500 Retry Exponential Backoff", "High"),
    ("Offline Sync", "Server-Wins Data Conflict Resolution Handler", "High"),
    ("Offline Sync", "Offline SQLite Historical Chart Renderer", "High"),
    ("Offline Sync", "Android Internal Cache Image Asset Storage", "Medium"),
    ("Offline Sync", "Room DB DAO Batch Insert (<10ms Benchmark)", "Medium"),
    ("Offline Sync", "Database Vacuum Maintenance Task on Startup", "Low"),
    ("Offline Sync", "50MB Max Offline Storage Cap Enforcement", "Medium"),
    ("Offline Sync", "Purge Offline Session Records Older Than 90 Days", "Low"),
    ("Offline Sync", "Offline Settings Changes Persistence Check", "High"),
    ("Offline Sync", "Sync Status Indicator Icon (Synced/Pending)", "Medium"),
    ("Offline Sync", "Manual 'Sync Now' Action Button Ingestion", "High"),
    ("Offline Sync", "JSON Batch Upload Payload Serialization", "High"),
    ("Offline Sync", "Partial Upload Failure Recovery Queueing", "High"),
    ("Offline Sync", "Database Corruption Auto-Recovery Re-Creation", "Medium"),
    ("Offline Sync", "Offline Local Report PDF File Generator", "Medium"),
    ("Offline Sync", "Local Offline Analytics Logic Parity Check", "High"),
    ("Offline Sync", "KeyStore Encryption Key Decryption Pass", "High"),
    ("Offline Sync", "Low Battery (<15%) Background Sync Suppression", "Medium"),
    ("Offline Sync", "Metered Data Saver Connection Sync Deferral", "Medium"),
    ("Offline Sync", "Standalone Offline Posture Alert Generator", "High"),
    ("Offline Sync", "Local Database Backup Export to .DB File", "Low"),

    # --- Mobile Dashboard & Native Charts (30) ---
    ("Mobile Dashboard", "MPAndroidChart Daily Posture Score Line Rendering", "High"),
    ("Mobile Dashboard", "Data Point Touch Marker Popup Display", "Medium"),
    ("Mobile Dashboard", "Weekly Slouch Bar Chart Entry Animation", "Medium"),
    ("Mobile Dashboard", "Circular Progress Health Grade Badge (A-F)", "High"),
    ("Mobile Dashboard", "Real-Time Posture Index Gauge Smooth Needle Move", "High"),
    ("Mobile Dashboard", "Top Summary Metric Cards (Score/Slouch/Breaks)", "High"),
    ("Mobile Dashboard", "Quick Action 'Start Live Tracking' Button Tap", "High"),
    ("Mobile Dashboard", "Quick Action 'Calibrate Camera' Button Tap", "High"),
    ("Mobile Dashboard", "Quick Action 'Upload Video' Button Tap", "High"),
    ("Mobile Dashboard", "Daily Posture Streak Counter Flame Animation", "Medium"),
    ("Mobile Dashboard", "Ergonomics Tip Card Horizontal Swipe Gesture", "Low"),
    ("Mobile Dashboard", "Layout Viewport Adaptation (5-inch vs 6.7-inch)", "High"),
    ("Mobile Dashboard", "Dashboard Drag-and-Drop Card Reordering", "Low"),
    ("Mobile Dashboard", "Dark Mode Native Chart Theme Adaptation", "High"),
    ("Mobile Dashboard", "Reset Pinch Zoom Viewport Action Button", "Medium"),
    ("Mobile Dashboard", "Zero Session Data Empty State Graphic Illustration", "Medium"),
    ("Mobile Dashboard", "Swipe Down Refresh Spinner Motion Feedback", "High"),
    ("Mobile Dashboard", "Health Risk Advisory Card for Low Posture Scores", "High"),
    ("Mobile Dashboard", "Tracking Time Duration Text Formatter", "Low"),
    ("Mobile Dashboard", "Time Range Tabs Switcher (Day/Week/Month)", "High"),
    ("Mobile Dashboard", "Active Session Tracking Banner Floating Bar", "High"),
    ("Mobile Dashboard", "Network Offline Mode Warning Badge Bar", "Medium"),
    ("Mobile Dashboard", "Achievement Unlocked Celebratory Toast Alert", "Low"),
    ("Mobile Dashboard", "Daily Target Progress Ring Percentage Calculation", "Medium"),
    ("Mobile Dashboard", "Social App Dashboard Image Share Dispatcher", "Low"),
    ("Mobile Dashboard", "Continuous 10-Minute Active View RAM Check", "Medium"),
    ("Mobile Dashboard", "High-Contrast Accessible Chart Mode Toggle", "Low"),
    ("Mobile Dashboard", "Floating Action Button Camera Quick Trigger", "High"),
    ("Mobile Dashboard", "Multi-Hour Tracking Score Precision Engine", "High"),
    ("Mobile Dashboard", "Smooth 60 FPS Native Chart Scroll Benchmark", "Medium"),

    # --- Media Library & Video Compression (25) ---
    ("Media Library", "READ_MEDIA_VIDEO Permission Request Dialog", "High"),
    ("Media Library", "System Media Picker Video File Selector", "High"),
    ("Media Library", "FFmpeg Hardware Accelerated Video Compression", "High"),
    ("Media Library", "4K 60FPS Video Transcoding Down to 720p 30FPS", "High"),
    ("Media Library", "File Size Savings Percentage Calculation", "Medium"),
    ("Media Library", "Video Trimmer Start/End Timestamp Selector", "Medium"),
    ("Media Library", "Video Player Play and Pause Controls", "High"),
    ("Media Library", "Seeker Bar Frame Thumbnail Hover Preview", "Medium"),
    ("Media Library", "Cloudinary Backend Video Upload Dispatch", "High"),
    ("Media Library", "Upload Percentage Notification Progress Bar", "High"),
    ("Media Library", "Background WorkManager Video Upload Task", "High"),
    ("Media Library", "Wi-Fi Only Video Upload Setting Restriction", "Medium"),
    ("Media Library", "Network Drop Mid-Upload Connection Retry", "High"),
    ("Media Library", "Video Analysis Processing Complete Push Alert", "High"),
    ("Media Library", "Landmark Skeleton Overlay Playback Sync", "High"),
    ("Media Library", "Post-Upload Video AI Report Card Display", "High"),
    ("Media Library", "Delete Uploaded Video File From Local Storage", "Medium"),
    ("Media Library", "Corrupted Video Bitstream Early Rejection", "High"),
    ("Media Library", "Upload Cancel Temp Swap File Cleanup", "Medium"),
    ("Media Library", "Maximum Video Length Limit (10 Minutes) Gate", "Medium"),
    ("Media Library", "Minimum Video Length Limit (5 Seconds) Gate", "Low"),
    ("Media Library", "Audio Channel Stripping for Privacy Protection", "High"),
    ("Media Library", "First Frame Keyframe Thumbnail Extraction", "Low"),
    ("Media Library", "Device Rotation Video Aspect Ratio Flip", "Medium"),
    ("Media Library", "Side-by-Side Video Posture Comparison View", "Low"),

    # --- System Permissions & Device Compatibility (20) ---
    ("System Permissions", "Permanent Permission Denied Settings Reroute", "High"),
    ("System Permissions", "Android Settings App Shortcut Button Launch", "High"),
    ("System Permissions", "Android 14 Granular Media Files Permission", "High"),
    ("System Permissions", "Android 12 Exact Alarm Permission Handling", "Medium"),
    ("System Permissions", "Location Permission Denial Fallback Gate", "High"),
    ("System Permissions", "Battery Optimization Exemption Request Flow", "High"),
    ("System Permissions", "Legacy External Storage Permission Check", "Medium"),
    ("System Permissions", "Voice Control Microphone Permission Dialog", "Low"),
    ("System Permissions", "App Resume Permission State Verification", "High"),
    ("System Permissions", "Background Camera Revocation Safety Catch", "High"),
    ("System Permissions", "Android Split Screen Multi-Tasking Reflow", "Medium"),
    ("System Permissions", "Foldable Device Screen Hinge Fold Event", "Low"),
    ("System Permissions", "10-inch Tablet Master-Detail Dual Pane View", "Medium"),
    ("System Permissions", "Android TV D-Pad Focus Navigation Support", "Low"),
    ("System Permissions", "Low Memory Device (<2GB RAM) Warning Handler", "High"),
    ("System Permissions", "Thermal Status Listener AI Engine Throttle", "High"),
    ("System Permissions", "System Dark Theme Auto-Switch Adaptation", "High"),
    ("System Permissions", "System Font Scaling Dynamic Text Resize", "Medium"),
    ("System Permissions", "Locale Switch String Localization Reload", "Medium"),
    ("System Permissions", "RTL Arabic Mirroring UI Orientation Check", "Low"),

    # --- Battery, Memory & Performance (20) ---
    ("Performance & Battery", "Cold Boot App Launch Time (<1.5s Benchmark)", "High"),
    ("Performance & Battery", "Warm Boot App Resume Time (<0.5s Benchmark)", "High"),
    ("Performance & Battery", "CPU Utilization During Active Camera Tracking (<25%)", "High"),
    ("Performance & Battery", "RAM Footprint During Active Tracking (<150MB)", "High"),
    ("Performance & Battery", "Zero Memory Leak Check After 50 Transitions", "High"),
    ("Performance & Battery", "Battery Drain Rate (<3% per 30 Mins)", "High"),
    ("Performance & Battery", "GPU Context Release on Camera View Destroy", "High"),
    ("Performance & Battery", "Background Service Passive Idle CPU (<1%)", "High"),
    ("Performance & Battery", "Network Data Traffic Consumption (<100KB/session)", "Medium"),
    ("Performance & Battery", "Zero ANR (Application Not Responding) Pass", "High"),
    ("Performance & Battery", "StrictMode Main Thread Disk I/O Check", "High"),
    ("Performance & Battery", "Bitmap Garbage Recycling OutOfMemory Safety", "High"),
    ("Performance & Battery", "SQLite Connection Pool Closure on Teardown", "Medium"),
    ("Performance & Battery", "ThreadPool Executor Shutdown on Exit", "Medium"),
    ("Performance & Battery", "List Scroll Smooth 60 FPS Frame Lock", "High"),
    ("Performance & Battery", "Low Battery (<15%) Auto FPS Reduction to 15 FPS", "High"),
    ("Performance & Battery", "Optimized APK Bundle Size (<35MB Package)", "Medium"),
    ("Performance & Battery", "ProGuard R8 Dead Code Stripping Check", "High"),
    ("Performance & Battery", "Native C++ OpenCV Memory Allocation Safety", "High"),
    ("Performance & Battery", "Garbage Collection Pause Duration (<10ms)", "Medium"),

    # --- Network Flakiness & Smartwatch Integration (40 Additional Unique Cases) ---
    ("Network Flakiness", "Network Handover 3G to 4G Request Retry", "High"),
    ("Network Flakiness", "Total Packet Loss Resilience Handling", "High"),
    ("Network Flakiness", "SSL Handshake Timeout Dialog Prompt", "Medium"),
    ("Network Flakiness", "Socket Connection Reset Graceful Catch", "High"),
    ("Network Flakiness", "Captive Portal Wi-Fi Detection Banner", "Medium"),
    ("Network Flakiness", "DNS Resolution Failure Fallback IP Connect", "High"),
    ("Network Flakiness", "Slow 2G Speed Connection Timeout Alert", "Medium"),
    ("Network Flakiness", "Mid-Upload Airplane Toggle Pause Queue", "High"),
    ("Network Flakiness", "VPN Network Adapter Switch Re-Handshake", "Medium"),
    ("Network Flakiness", "IPv6 Dual-Stack Network Socket Failover", "Low"),

    ("Smartwatch Wear OS", "Smartwatch BLE Discovery and Pairing Flow", "High"),
    ("Smartwatch Wear OS", "Slouch Warning Wrist Vibration Sync", "High"),
    ("Smartwatch Wear OS", "Watch Face Complication Score Indicator", "Medium"),
    ("Smartwatch Wear OS", "Heart Rate Sensor Stress Correlation Sync", "Medium"),
    ("Smartwatch Wear OS", "Quick Tile 'Pause Tracking' Remote Trigger", "Medium"),
    ("Smartwatch Wear OS", "Standalone Smartwatch Posture Mode Without Phone", "High"),
    ("Smartwatch Wear OS", "Ambient Low-Power Watch Display Mode", "Low"),
    ("Smartwatch Wear OS", "Smartwatch Notification Dismiss Handheld Sync", "Medium"),
    ("Smartwatch Wear OS", "Watch Battery Drain Rate (<2%/hr) Test", "Medium"),
    ("Smartwatch Wear OS", "Wrist Sensor Zero Alignment Tap Prompt", "Low"),

    ("Multi-Language Localization", "Spanish Language Dashboard String Set", "Medium"),
    ("Multi-Language Localization", "French Language Calibration Screen Text", "Medium"),
    ("Multi-Language Localization", "German Language Settings Screen Layout", "Medium"),
    ("Multi-Language Localization", "Japanese Kana Text Rendering Clip Check", "Low"),
    ("Multi-Language Localization", "Chinese Simplified Character Set Encoding", "Low"),
    ("Multi-Language Localization", "Hindi Language Alert Settings Strings", "Medium"),
    ("Multi-Language Localization", "Portuguese Decimal Formatter (Comma Sep)", "Low"),
    ("Multi-Language Localization", "RTL Arabic Navigation Layout Mirroring", "Medium"),
    ("Multi-Language Localization", "Localized Date-Time Format Parsing", "Medium"),
    ("Multi-Language Localization", "Localized Currency Symbol Billing Page", "Low"),

    ("App Lifecycle & Intent", "Low Memory Killer Process State Restore", "High"),
    ("App Lifecycle & Intent", "Custom Scheme Deep Link (posturefix://)", "High"),
    ("App Lifecycle & Intent", "Universal Web Link Navigation Handler", "High"),
    ("App Lifecycle & Intent", "Mandatory Forced App Update Gate Screen", "High"),
    ("App Lifecycle & Intent", "In-App Play Store Review Trigger Prompt", "Low"),
    ("App Lifecycle & Intent", "Launcher Quick Action Long-Press Menu", "Medium"),
    ("App Lifecycle & Intent", "Android Native Splash Screen Motion", "Low"),
    ("App Lifecycle & Intent", "AlarmManager Scheduled Background Task", "Medium"),
    ("App Lifecycle & Intent", "Double-Tap Back Exit Confirmation Dialog", "Low"),
    ("App Lifecycle & Intent", "Notification Payload Launch Parameter Intent", "High"),
]
